Vagrant.configure(2) do |config|
  config.vm.box = "geerlingguy/centos7"
  config.vm.hostname = "ci-server"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.synced_folder "../", "/var/data",create: true
  config.vm.provider "virtualbox" do |v|
    # Add a name
    v.name="CI_Env"
    # Add enough memory
    v.memory = 4048
  end
  config.vm.provision :ansible_local do |ansible|
    ansible.playbook="provisionning/configure-ci-server.yml"
    ansible.config_file="provisionning/ansible.cfg"
  end
end

