---
# Optional method of pinning a specific version of Jenkins and/or overriding the
# default Jenkins packaging URL.
# jenkins_version: "1.644"
# jenkins_pkg_url: "https://www.example.com"

# Change this to `latest` to update Jenkins if a newer version is available.
jenkins_package_state: present

jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_home: /var/lib/jenkins
jenkins_hostname: localhost
jenkins_http_port: 8080
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_url_prefix: ""
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"

jenkins_plugins:
  - git
  - ssh-slaves
  - role-strategy       # Role Based Authorization Strategy
  - cloudbees-folder    # Add folders fetaure
  - copyartifact
  - ldap
  - build-timestamp
  - ownership           # Define owners for jobs and nodes
  - read-only-configurations    # Allow configuration read for users that have not the configuration authorization
  - parameterized-trigger
  - build-timeout
  - email-ext           # Offer emails with attachments, variables expansion...
  - simple-parameterized-builds-report    # Useful for build chain with some sort of Build unique id var
  - groovy
  - groovy-postbuild
  - pipeline-model-definition    # For pipeline jobs : lots of other Pipeline:xxxx plugins will be installed
  - blueocean           # New GUI for pipeline jobs, including an editor.

jenkins_plugins_state: present
jenkins_plugin_updates_expiration: 86400
jenkins_plugin_timeout: 30

jenkins_admin_username: admin
jenkins_admin_password: lookup('passwordstore', 'n0ts0S3cr3t.tmpl')
jenkins_admin_password_file: ""
jenkins_admin_token: ""
jenkins_admin_token_file: ""

jenkins_process_user: jenkins
jenkins_process_group: "{{ jenkins_process_user }}"

jenkins_init_changes:
  - option: "JENKINS_ARGS"
    value: "--prefix={{ jenkins_url_prefix }}"
  - option: "{{ jenkins_java_options_env_var }}"
    value: "{{ jenkins_java_options }}"
