- name: Configure CI server
  hosts: ci-server
  sudo: True
  roles:
    - git
    - role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk
    - LTS-2_89.jenkins

